### ISSUE TITLE
Issue Installing dependencies to build out astro website

### ISSUE THREAD

**Issue by timeowilliams** [RocketCommunicationsInc/astro#260]
Requesting a change in dependencies as I failed to complete the npm install script for this [repo.](https://github.com/RocketCommunicationsInc/astro/tree/main/packages/astro-uxds) 

Current OS:  MacOS BigSur 11.5.2 (20G95)
Processor: Intel Core i5

Steps to reproduce issue: 

1. In any directory: 
```
git clone git@github.com:RocketCommunicationsInc/astro-uxds.git
cd astro-uxds
```

2. `npm install`

See output: 

<img width="563" alt="image" src="https://user-images.githubusercontent.com/19152894/154735831-5c716321-a9f9-47dd-a825-3099992f1c7d.png">

**Comment by micahjones13** [comment]
Thanks for raising this! It turns out we forgot to update the README.md of the astro-uxds repo; we've since moved it into the mono-repo. To get the updated version, you can clone the [astro mono-repo](https://github.com/RocketCommunicationsInc/astro) with 
```
git clone git@github.com:RocketCommunicationsInc/astro.git
cd packages/astro-uxds
npm install
```
We've also replaced node-sass with sass in the astro-uxds package, so hopefully that will get rid of your error above. 
We do realize that it's a hefty install, especially if you are just interested in one of the packages and not the entirety of the mono-repo. We've been considering moving astro-uxds back out into it's own repo, so we'd be curious to know what your use case is with it so we can make a more informed decision. 

Please let me know if you need anything else!

**Comment by timeowilliams** [comment]
Excellent - thanks @micahjones13
