### ISSUE TITLE
Support a message-content slot within rux-modal

### ISSUE THREAD

**Issue by QGerrit** [RocketCommunicationsInc/astro#398]
Currently, a `<rux-modal>` element has a `modal-message` attribute which sets the message. This is very convenient for simple modals, but sometimes it would be nice to be able to include rich content (e.g. a link to help documentation with more details). Ideally, this should be achievable via a custom slot. Thoughts?

**Comment by markacianfrani** [comment]
Absolutely! We've actually already done this and reworked modal to be entirely composable with slots. Unfortunately, it's a breaking change so it's currently in our 7.0 next branch. We'll be releasing a new beta tomorrow. We're going to revisit backporting this change to 6.0 in the meantime because the current modal implementation isn't very flexible.

**Comment by QGerrit** [comment]
That's awesome, thank you @markacianfrani!

**Comment by micahjones13** [comment]
Hey @QGerrit, just wanted to check in and say that a re-work of modal has just been merged to main that contains the option to use slots for all of the modal's parts, so you can customize it as much as you want. This will be released tomorrow in the latest version (6.8). 
Hopefully this helps, and if you have any questions please reach out again!

**Comment by QGerrit** [comment]
Awesome, thank you @micahjones13!
