### ISSUE TITLE
rux-modal should have a maximum height

### ISSUE THREAD

**Issue by QGerrit** [RocketCommunicationsInc/astro#470]
We had a reasonably large amount of content in a rux-modal, and on a smaller screen noticed that it overflowed, so there was no way to close the modal.

Suggestion:
- Apply a max-height to the message slot so that the close button is always visibile

![image](https://user-images.githubusercontent.com/97202638/174403603-fd65093b-1b24-4ffe-ba3e-035e7a30a2a5.png)

**Comment by micahjones13** [comment]
Hey there,

If you are able to switch to using the default slot, I think you're issue could be solved with this approach - https://codesandbox.io/s/flamboyant-khayyam-68xs0r?file=/index.html

We are looking to provide better support for scrollbars in rux-modal in the future, but maybe this could work for now? 
Let me know if this helps, or if you're not able to switch to using a slot instead of the `modal-message` prop.

**Comment by micahjones13** [comment]
I've just updated that sandbox above to also show an option using our CSS shadow parts to add a max-height to the modal message. If you can't switch to slots (which I would recommend), then hopefully that can fix the issue for you!

**Comment by QGerrit** [comment]
Thanks! Yes, I am using slots. The overflow approach is exactly what I plan to use if I run into this again before your team gets around to it :) I was able to rework some of the modal content to take up less space.
