### ISSUE TITLE
rux-pop-up-menu does not render in <mat-drawer>

### ISSUE THREAD

**Issue by tallen30** [RocketCommunicationsInc/astro#494]
When the rux-pop-up-menu is used in the mat-drawer (see https://material.angular.io/components/sidenav/api) it does not render properly. The menu looks like it tries to put it on the container but ends up somewhere else on the application.

**Comment by VincentQDo** [comment]
Please see this sandbox example [here](https://codesandbox.io/s/rux-pop-up-mat-drawer-6-9-forked-rxxu5t?file=/src/app/app.component.html). When using with position="end". The pop up menu is trying to come up but is being put way off screen I think.

**Comment by micahjones13** [comment]
Alright, I have some findings.

The pop up is not aligning itself relative to the mat-drawer and the trigger element, but instead relative to the entire page. This is placing it in really whacky places within mat-drawer.  Good news is, in our upcoming 7.0 release this isn't an issue as we've re-worked pop-up. Here's a sandbox example [of 7.0 working here](https://codesandbox.io/s/rux-pop-up-mat-drawer-7-0-qpvp3j?file=/src/app/app.component.html).

Bad news is, the release date for 7.0 has been pushed backed, and we're still solidifying the new release date. I will reply here with that date when it becomes known.

In the meantime, you may be able to set the bounding of the pop-up menu yourself. It's pretty hacky, but here's an example [sandbox if you're interested](https://codesandbox.io/s/rux-pop-up-mat-drawer-6-9-hack-b6eosd?file=/src/app/app.component.ts).

Sorry I don't have happier news, but a fix for this isn't on our roadmap in version 6 since it's solved in 7. I'll make sure to get back here with a 7.0 release date when I have one.

**Comment by micahjones13** [comment]
7.0 release update: we're shooting for 9/29, one week from today. When 7 is released, these pop-up woes should be resolved. 
Thanks for your patience!
