### ISSUE TITLE
RuxSlider doesn't expose onRuxChange event

### ISSUE THREAD

**Issue by EzraBrooks** [RocketCommunicationsInc/astro#609]
I'm using the React bindings.
I have a slider that is attached to a fairly heavy computation, and don't want to wire it up to high-rate changes from user interaction with the slider element. `onChange` doesn't seem to work, and `onRuxChange` doesn't seem to exist. I could debounce it, which would get me almost to the correct behavior, but it seems like this should probably have an event that fires when the change is committed.

**Comment by micahjones13** [comment]
Hey @EzraBrooks , you should be able to use `onRuxinput` to listen for changes on the slider. The reason for this is listed here [in our React wrapper docs](https://astro-components.netlify.app/?path=/story/astro-uxds-welcome-react--page#listening-to-events). Long story short, React and native have different names for onChange, and since our web components are based off the native range input type, we use the input event. 
Let me know if that solves it or if you have any other questions!

**Comment by EzraBrooks** [comment]
`input` and `change` are different, correct? `input` fires immediately on user interaction and `change` fires upon the committing of the value? I don't think `input` is useful to me in this context due to the compute overhead of the handler. Debouncing it would reduce the compute overhead but it would still do weird things if the user moused down, dragged, and then paused and thought for a second before mousing up - a debounced input event would still call the event handler even though the user wasn't ready.

**Comment by micahjones13** [comment]
That's an excellent point! I'm going to create a ticket to add the onChange event, and we will include it in our next release which will be this Thursday. If the need is severe, you may be able to utilize the `onRuxblur` event in order to run the computations after the value has been set - but I know that's not ideal.

**Comment by micahjones13** [comment]
This event has been added and will be released with version 6.12 this Thursday (08/4).
