### ISSUE TITLE
Icons for date/time pickers do not show up in Firefox

### ISSUE THREAD

**Issue by QGerrit** [RocketCommunicationsInc/astro#699]
If I go to https://astro-components.netlify.app/?path=/story/forms-input--types on Chrome I see

![image](https://user-images.githubusercontent.com/97202638/188205661-110d6b4c-ea37-4219-bd3d-c3204ce8dc78.png)

The same page on Firefox shows:

![image](https://user-images.githubusercontent.com/97202638/188205698-49d250d2-90bc-4036-86ab-258f143c04d7.png)

**Comment by micahjones13** [comment]
Hey @QGerrit! 

This is because of they way Firefox handles native inputs. If you take a look at [this page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) on Chrome, you'll see the calendar icon. If you look at it on Firefox, that icon isn't there.

Our input component uses the native HTML input element under the hood and because of that the icons in some types of inputs are visible in Chrome but not in Firefox. Because Chrome does provide it, we're able to style it to match Astro - but since Firefox doesn't, there's nothing to style.

There may be a way to add our icon to the input if the browser is Firefox, but we haven't looked too much into it yet.

**Comment by QGerrit** [comment]
Ah, that's unfortunate! That's good to know, this makes sense... it's probably not worth the effort to write custom pickers in every case. The time picker in particular isn't very useful in Chrome in my experience.
