### ISSUE TITLE
Pop up menu doesn't close after selection

### ISSUE THREAD

**Issue by run2xs** [RocketCommunicationsInc/astro#821]
The default behavior on the popup menu should be that it automatically closes after a selection has been made.  If a client wants to enable mult-select on the menu or for some other reason wants to control it manually, then a property should be used to indicate that behavior.   In that case, the popup won't close until it is programatically done so.

We don't need anything rolled back for this.  Our workaround is fine for now, but I think this should be the default behavior.

**Comment by micahjones13** [comment]
Because changing the default behavior to pop-up closing on a selection would be considered a breaking change, we've added a `close-on-select` prop to `rux-pop-up` that will provide this functionality. We'll definitely evaluate making this the default behavior in the next major version, though.
This new prop will be available in the release tomorrow, version 7.0.3.
Thanks for bringing this up!
