### ISSUE TITLE
rux-clock component is misaligned when labels are hidden

### ISSUE THREAD

**Issue by nortonprojects** [RocketCommunicationsInc/astro#999]
**Describe the bug**
When labels are hidden from the rux-clock component, it stays top-aligned. The clock height should shrink to match, or the content should be center-justified.

**To Reproduce**

1. Go to 'https://astro-components.netlify.app/?path=/story/components-clock--other-variants&args=hideLabels:true'
3. Scroll down to 'Hide Labels'
4. See error in inspector

**Environment (please complete the following information):**

- chrome
- 7.0.0
-  Angular
- @astrouxds/angular

**Additional context**

**Comment by micahjones13** [comment]
Hey Jacob, thanks for raising this! Looks like we have a set height on clock, so that's why it's retaining it's full height rather than collapsing to fit when `hide-labels` is true. I'm going to address that and make a PR real quick!

As for the console error, that's Storybook related and not anything to do with our component. Only the default stories can be wired up to controls in Storybook, so if you're viewing an 'All Variants' page and have a query param string that usually toggles a control, you'll see that warning in the console.
